openapi: 3.0.1
info:
  title: '@jupiterone/graph-sentry'
  description: JupiterOne integration for ingesting data from Sentry.io
  x-cortex-git:
    github:
      repository: JupiterOne/graph-sentry
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-sentry'
  x-cortex-service-groups:
    - tier-4
